//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALLINSHOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admintrator
    {
        internal string errorMessage;

        public System.Guid Admin_ID { get; set; }
        public string Admin_Name { get; set; }
        public string Admin_Pa { get; set; }
    }
}
